name: Check PO Syntax

on:
  pull_request:
    branches: [ "**" ]
  push:
    branches: [ "**" ]

jobs:
  check-po:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install gettext
        run: sudo apt-get update && sudo apt-get install -y gettext

      - name: Validate PO files with msgfmt
        run: |
          find . -name "*.po" -exec msgfmt --check --check-format -o /dev/null {} +
